apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keda-alpha
  namespace: operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: keda
  source: operatorhubio-catalog
  sourceNamespace: olm
  startingCSV: keda.v2.7.1