apiVersion: operators.coreos.com/v1
kind: OLMConfig
metadata:
  name: cluster
spec:
  features:
    disableCopiedCSVs: true # Disabled Copied CSVs for AllNamespace operators. (https://olm.operatorframework.io/docs/advanced-tasks/configuring-olm/)